apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # $ echo -n <string> | base64
  POSTGRES_DB: cG9zdGdyZXNkYg==
  POSTGRES_USER: cG9zdGdyZXNhZG1pbg==
  POSTGRES_PASSWORD: YWRtaW4xMjM=